name: grec_minimal
description: A minimal parser/generator of recurrence rule for Google Calendar
version: 0.0.1
homepage: https://github.com/moznion/dart-grec-minimal
author: moznion <moznion@gmail.com>

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dev_dependencies:
  test: ^0.12.30
